### ISSUE TITLE
Move to same block level

### ISSUE THREAD

**Issue by rswgnu** [nixin72/block-nav.el#1]
I think the main movement in the video you referred to was to move to the nextblock at the same level as point,  not any more deeply nested one, so you might want to add that too.  In Python, if-then-else statements and try-except-finally statements would show the utility.

**Comment by nixin72** [comment]
The `block-nav-next-block` and `block-nav-previous-block` do that. I suppose I should've used something that's not Lisp to showcase it since it can have weird indentation though... 
![simplescreenrecorder-2020-09-27](https://user-images.githubusercontent.com/22285063/94373214-d95f5300-00d1-11eb-9245-183c0ab32695.gif)

Again, I apologize for the poor video quality...

**Comment by rswgnu** [comment]
Just tested this and found these issues:

1. Emacs 27.1, current-line-contents function is not defined.  I made my own to fill it in.

2. If you are at the beginning of the last line of a block, the next command moves to the next higher level beginning of block and resets the level at which to navigate.  More consistent would be to skip over higher-level blocks and move to the next same level block (or don't move at all).

3.  If the line moved to is already on-screen, don't scroll.  It is jarring and unneeded.

With a few changes, you'll be there.

**Comment by nixin72** [comment]
Thanks for the comments! The `current-line-contents` issue just got fixed by #2, so sorry about that, I didn't realize that function was coming from another package. 

For 2, I can definitely change that up! I'll add a variable to make the behaviour customizable, and I can set that as the default behaviour. 

To address point 3 about the scrolling, there's a variable that changes that behaviour, the `block-nav-center-after-scroll`. I personally like it, so I'd like to include it as an option, but I'll definitely make the default value `nil` if you think that most people won't appreciate that :ok_hand: 

I really appreciate the comments, I've never made a package for Emacs before and am fairly new to it, so I don't know what people like!

**Comment by rswgnu** [comment]
I agree with all of these ideas.  Sounds good.  You are doing well for a first timer thanks to your other experience.

Also, you should add the standard GPL license at the top of the code you can find in any standard Emacs Lisp file.

**Comment by rswgnu** [comment]
Oh, and add doc strings to each of your functions.

**Comment by kadircancetin** [comment]
Also, I highly suggest that you should try to add the package to melpa. They have strict rules that make the package more standard. They have very welcome contributors. GPL and docstrings are musts like @rswgnu suggested.

**Comment by nixin72** [comment]
Thank you @rswgnu! I'll change license to GPL and add the blurb to the top of the file, add docstrings, then get started on the other changes above. 

@kadircancetin I plan to try adding the package to melpa once I get it to a more complete state for sure :ok_hand: I was looking into the requirements for that yesterday.

**Comment by nixin72** [comment]
Okay, so I just merged in PR #5 which adds the `block-nav-move-skip-shallower` variable. When true, it'll skip over any lines that have a shallower indentation level than the current line. 

There's also a `block-nav-center-after-scroll` variable, that when true, will recenter the current line in the window after doing the moves. 

Haven't had time to work on this the past couple days, but going to look into what's required for melpa now to get it ready for that.

**Comment by nixin72** [comment]
Thank you everyone for your suggestions for this package, I really appreciate them! The package has now been [added to MELPA](https://melpa.org/#/block-nav)!
